baseURL = "https://gdev-peter.github.io/"	# Needs to be replaced later
title = "UCCS"

theme = "uccs-theme-a"

defaultContentLanguage = "ro"
languageCode = "ro-RO"

enableRobotsTXT = false

# Good practice: keep generated URLs stable
canonifyURLs = false
relativeURLs = false

# Optional but useful
pagerSize = 12
summaryLength = 30

[caches]
  [caches.images]
    dir = ':cacheDir/images'