[[main]]
name = "Polis"
pageRef = "/polis"
weight = 10

[[main]]
name = "Agora"
pageRef = "/agora"
weight = 20

[[main]]
name = "Educație"
pageRef = "/educatie"
weight = 30

[[main]]
name = "Tech"
pageRef = "/tech"
weight = 40

[[main]]
name = "Litere"
pageRef = "/litere"
weight = 50

[[main]]
name = "Despre"
pageRef = "/despre"
weight = 80

[[main]]
name = "Contact"
pageRef = "/contact"
weight = 90

[[main]]
name = "Donează"
pageRef = "/doneaza"
weight = 100
