description = "Proiect editorial independent cu substanță, nu doar formă."
author = "Redacția UCCS"

# If theme supports social links
[social]
instagram = "https://www.instagram.com/istorie.petru/"
donateURL = "https://www.instagram.com/istorie.petru/."
